name: Build and Deploy to Firebase
"on":
  push:
    branches:
      - main
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_FIREBASE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Decode Google Service Account
        run: echo $GOOGLE_FIREBASE_SERVICE_ACCOUNT | base64 --decode > ${GITHUB_WORKSPACE}/firebase-service-account.json

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        run: firebase auth:login --token "$(cat ${GITHUB_WORKSPACE}/firebase-service-account.json)" --account ${GITHUB_WORKSPACE}/firebase-service-account.json

      - name: Use Firebase development environment
        run: firebase use dev

      - name: Deploy to Firebase
        run: firebase deploy --only functions --debug
