name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create credentials.json from secret
        id: create-json
        run: echo "${{ secrets.GOOGLE_FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > credentials.json

      - name: Set environment variable with path to credentials.json
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json" >> $GITHUB_ENV

      - name: Use Firebase development environment
        shell: bash
        run: firebase use dev

      - name: Deploy to Firebase
        shell: bash
        run: firebase deploy --only functions --debug
