name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_FIREBASE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode and save Google Service Account
        run: echo ${{ secrets.GOOGLE_FIREBASE_SERVICE_ACCOUNT }} | base64 -d > $HOME/firebase-service-account.json

      - name: Set up Google Application Credentials
        run: echo "export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json" >> $GITHUB_ENV

      - name: Use Firebase development environment
        run: firebase use dev

      - name: Deploy to Firebase
        run: firebase deploy --only functions --debug