name: Build and Deploy to Firebase
"on":
  push:
    branches:
      - main
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Use Firebase development environment
        shell: bash
        run: firebase use dev

      - name: Deploy to Firebase
        shell: bash
        run: firebase deploy --only functions --debug
