name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_FIREBASE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Google Service Account
        env:
          DATA: ${{ secrets.GOOGLE_FIREBASE_SERVICE_ACCOUNT }}
        run: echo $DATA | base64 -d > ${HOME}/google-services.json

      - name: Authenticate with Firebase
        run: firebase auth:import --service-account ${HOME}/google-services.json

      - name: Use Firebase development environment
        run: firebase use dev

      - name: Deploy to Firebase
        run: firebase deploy --only functions --debug